version: 2

sphinx:
  configuration: docs/conf.py

conda:
  environment: environment.yml

python:
  version: 3.7
  install:
    - method: pip
      path: .
    - method: setuptools
  system_packages: true

