version: 2

# https://docs.readthedocs.io/en/stable/guides/conda.html#making-builds-faster-with-mamba
build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"

sphinx:
  configuration: docs/conf.py

conda:
  environment: environment.yml

python:
  install:
    - method: pip
      path: .
