language: python
python:
  - "3.6"
before_install:
  # adapted from the Qurro .travis.yml file
  # 1. Install conda (commands from
  # https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html)
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  # 2. Install the latest QIIME 2 version
  # (see https://dev.qiime2.org/latest/quickstart, thanks @thermokarst for
  # the heads up :)
  - wget https://raw.githubusercontent.com/qiime2/environment-files/master/latest/staging/qiime2-latest-py36-linux-conda.yml
  - travis_retry conda env create -n qiime2-dev --file qiime2-latest-py36-linux-conda.yml
  - source activate qiime2-dev
  - conda install -c conda-forge pystan
  - conda install -c conda-forge pytest-mock
install:
  - pip install -e .[dev]
script:
  - python tests/data/moving_pictures_example.py
  - pytest
