name: birdman
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - pandas
  - numpy
  - python=3.8
  - python-language-server
  - xarray
  - patsy
  - biom-format
  - cmdstanpy
  - arviz
  - docutils==0.16
  - pip:
    - sphinx-rtd-theme==0.5.1
